
package Vistass;

public class AgregarSesion extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarSesion
     */
    public AgregarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jtfFechaFin = new javax.swing.JTextField();
        jbBuscarSesion = new javax.swing.JButton();
        jtfCodTratamiento = new javax.swing.JTextField();
        jtfCodMasajista = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jlFechaInicio = new javax.swing.JLabel();
        jlFechaFin = new javax.swing.JLabel();
        jlGestionClientes = new javax.swing.JLabel();
        jlCodTratamiento = new javax.swing.JLabel();
        jlCodMasajista = new javax.swing.JLabel();
        jtfFechaInicio = new javax.swing.JTextField();
        jtfCodDiaSpa = new javax.swing.JTextField();
        jlCodDiaSpa = new javax.swing.JLabel();
        jtfCodInstalacion = new javax.swing.JTextField();
        jlCodInstalacion = new javax.swing.JLabel();
        jlEstadoInstalacion = new javax.swing.JLabel();
        jcbEstadoInstalacion = new javax.swing.JComboBox<>();
        jbGuardarSesion = new javax.swing.JButton();
        jbActualizarSesion = new javax.swing.JButton();
        jbEliminarSesion = new javax.swing.JButton();
        jbCambiarEstadoSesion = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);

        jtfFechaFin.setEditable(false);
        jtfFechaFin.setForeground(new java.awt.Color(69, 54, 14));
        jtfFechaFin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));
        jtfFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFechaFinActionPerformed(evt);
            }
        });

        jbBuscarSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbBuscarSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbBuscarSesion.setText("Buscar");
        jbBuscarSesion.setBorder(null);

        jtfCodTratamiento.setEditable(false);
        jtfCodTratamiento.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodTratamiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));
        jtfCodTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodTratamientoActionPerformed(evt);
            }
        });

        jtfCodMasajista.setEditable(false);
        jtfCodMasajista.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodMasajista.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setText("Spa Entre Dedos");

        jlFechaInicio.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlFechaInicio.setForeground(new java.awt.Color(69, 54, 14));
        jlFechaInicio.setText("Fecha de incio:");

        jlFechaFin.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlFechaFin.setForeground(new java.awt.Color(69, 54, 14));
        jlFechaFin.setText("Fecha de finalizacion:");

        jlGestionClientes.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jlGestionClientes.setText("Gestion Sesiones");

        jlCodTratamiento.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodTratamiento.setForeground(new java.awt.Color(69, 54, 14));
        jlCodTratamiento.setText("Codigo tratamiento:");

        jlCodMasajista.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodMasajista.setForeground(new java.awt.Color(69, 54, 14));
        jlCodMasajista.setText("Codigo Masajista:");

        jtfFechaInicio.setEditable(false);
        jtfFechaInicio.setForeground(new java.awt.Color(69, 54, 14));
        jtfFechaInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jtfCodDiaSpa.setEditable(false);
        jtfCodDiaSpa.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodDiaSpa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));
        jtfCodDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodDiaSpaActionPerformed(evt);
            }
        });

        jlCodDiaSpa.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodDiaSpa.setForeground(new java.awt.Color(69, 54, 14));
        jlCodDiaSpa.setText("Codigo Dia de Spa:");

        jtfCodInstalacion.setEditable(false);
        jtfCodInstalacion.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodInstalacion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jlCodInstalacion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodInstalacion.setForeground(new java.awt.Color(69, 54, 14));
        jlCodInstalacion.setText("Codigo Instalacion:");

        jlEstadoInstalacion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlEstadoInstalacion.setForeground(new java.awt.Color(69, 54, 14));
        jlEstadoInstalacion.setText("Estado:");

        jcbEstadoInstalacion.setBackground(new java.awt.Color(242, 242, 242));
        jcbEstadoInstalacion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jcbEstadoInstalacion.setForeground(new java.awt.Color(69, 97, 11));
        jcbEstadoInstalacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstadoInstalacion.setBorder(null);

        jbGuardarSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbGuardarSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbGuardarSesion.setText("Guardar");
        jbGuardarSesion.setBorder(null);
        jbGuardarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarSesionActionPerformed(evt);
            }
        });

        jbActualizarSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbActualizarSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbActualizarSesion.setText("Actualizar");
        jbActualizarSesion.setBorder(null);
        jbActualizarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarSesionActionPerformed(evt);
            }
        });

        jbEliminarSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbEliminarSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbEliminarSesion.setText("Eliminar");
        jbEliminarSesion.setBorder(null);
        jbEliminarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarSesionActionPerformed(evt);
            }
        });

        jbCambiarEstadoSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbCambiarEstadoSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbCambiarEstadoSesion.setText("Cambiar Estado");
        jbCambiarEstadoSesion.setBorder(null);
        jbCambiarEstadoSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarEstadoSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlCodInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jtfCodMasajista, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCodMasajista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfCodInstalacion)
                                    .addComponent(jbGuardarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbActualizarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfCodDiaSpa, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlCodDiaSpa, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jbCambiarEstadoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jlEstadoInstalacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbEstadoInstalacion, javax.swing.GroupLayout.Alignment.LEADING, 0, 159, Short.MAX_VALUE)
                                            .addComponent(jbEliminarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfFechaFin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfFechaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlFechaInicio, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlCodTratamiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfCodTratamiento)
                                    .addComponent(jbBuscarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlGestionClientes)
                                .addGap(74, 74, 74)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionClientes)
                .addGap(26, 26, 26)
                .addComponent(jlFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBuscarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFechaFin)
                    .addComponent(jlCodTratamiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCodTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCodDiaSpa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCodMasajista)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCodDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEstadoInstalacion)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlCodInstalacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEstadoInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCambiarEstadoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodTratamientoActionPerformed

    private void jtfCodDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodDiaSpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodDiaSpaActionPerformed

    private void jtfFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaFinActionPerformed

    private void jbGuardarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarSesionActionPerformed

    }//GEN-LAST:event_jbGuardarSesionActionPerformed

    private void jbActualizarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarSesionActionPerformed

    }//GEN-LAST:event_jbActualizarSesionActionPerformed

    private void jbEliminarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarSesionActionPerformed

    }//GEN-LAST:event_jbEliminarSesionActionPerformed

    private void jbCambiarEstadoSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarEstadoSesionActionPerformed

    }//GEN-LAST:event_jbCambiarEstadoSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbActualizarSesion;
    private javax.swing.JButton jbBuscarSesion;
    private javax.swing.JButton jbCambiarEstadoSesion;
    private javax.swing.JButton jbEliminarSesion;
    private javax.swing.JButton jbGuardarSesion;
    private javax.swing.JComboBox<String> jcbEstadoInstalacion;
    private javax.swing.JLabel jlCodDiaSpa;
    private javax.swing.JLabel jlCodInstalacion;
    private javax.swing.JLabel jlCodMasajista;
    private javax.swing.JLabel jlCodTratamiento;
    private javax.swing.JLabel jlEstadoInstalacion;
    private javax.swing.JLabel jlFechaFin;
    private javax.swing.JLabel jlFechaInicio;
    private javax.swing.JLabel jlGestionClientes;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfCodDiaSpa;
    private javax.swing.JTextField jtfCodInstalacion;
    private javax.swing.JTextField jtfCodMasajista;
    private javax.swing.JTextField jtfCodTratamiento;
    private javax.swing.JTextField jtfFechaFin;
    private javax.swing.JTextField jtfFechaInicio;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
