
package Vistass;

import Modeloo.Conexion;
import Modeloo.Masaje;
import Modeloo.TipoMasaje;
import Persistencia.MasajeData;
import javax.swing.JOptionPane;
import org.mariadb.jdbc.Connection;

public class AgregarMasaje extends javax.swing.JInternalFrame {

    private MasajeData masajeData;

    public AgregarMasaje() {
        initComponents();
        masajeData = new MasajeData((Connection) Conexion.getConexion());
        
        for (TipoMasaje tipo : TipoMasaje.values()) {
            jcbTipoDeMasaje.addItem(tipo);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jtfDetalleMasaje = new javax.swing.JTextField();
        jcbTipoDeMasaje = new javax.swing.JComboBox<>();
        jcbEstadoMasaje = new javax.swing.JComboBox<>();
        jbBuscarMasaje = new javax.swing.JButton();
        jtfDuracionMasaje = new javax.swing.JTextField();
        jtfCostoMasaje = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jlNombreMasaje = new javax.swing.JLabel();
        jlDetalleMasaje = new javax.swing.JLabel();
        jlGestionMasajes = new javax.swing.JLabel();
        jlDuracionMasaje = new javax.swing.JLabel();
        jlTipoDeMasaje = new javax.swing.JLabel();
        jlCostoMasaje = new javax.swing.JLabel();
        jtfNombreMasaje = new javax.swing.JTextField();
        jlEstadoMasaje = new javax.swing.JLabel();
        jbCambiarEstadoMasaje = new javax.swing.JButton();
        jbGuardarMasaje = new javax.swing.JButton();
        jbActualizarMasajes = new javax.swing.JButton();
        jbEliminarMasaje = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);

        jtfDetalleMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jtfDetalleMasaje.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jcbTipoDeMasaje.setBackground(new java.awt.Color(242, 242, 242));
        jcbTipoDeMasaje.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jcbTipoDeMasaje.setForeground(new java.awt.Color(69, 97, 11));
        jcbTipoDeMasaje.setBorder(null);

        jcbEstadoMasaje.setBackground(new java.awt.Color(242, 242, 242));
        jcbEstadoMasaje.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jcbEstadoMasaje.setForeground(new java.awt.Color(69, 97, 11));
        jcbEstadoMasaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstadoMasaje.setBorder(null);
        jcbEstadoMasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoMasajeActionPerformed(evt);
            }
        });

        jbBuscarMasaje.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbBuscarMasaje.setForeground(new java.awt.Color(69, 97, 11));
        jbBuscarMasaje.setText("Buscar");
        jbBuscarMasaje.setBorder(null);
        jbBuscarMasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarMasajeActionPerformed(evt);
            }
        });

        jtfDuracionMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jtfDuracionMasaje.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));
        jtfDuracionMasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDuracionMasajeActionPerformed(evt);
            }
        });

        jtfCostoMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jtfCostoMasaje.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jlNombreMasaje.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlNombreMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jlNombreMasaje.setText("Nombre:");

        jlDetalleMasaje.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlDetalleMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jlDetalleMasaje.setText("Detalles:");

        jlGestionMasajes.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlGestionMasajes.setForeground(new java.awt.Color(69, 97, 11));
        jlGestionMasajes.setText("Gestion Masajes");

        jlDuracionMasaje.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlDuracionMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jlDuracionMasaje.setText("Duracion:");

        jlTipoDeMasaje.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlTipoDeMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jlTipoDeMasaje.setText("Tipo:");

        jlCostoMasaje.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCostoMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jlCostoMasaje.setText("Costo:");

        jtfNombreMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jtfNombreMasaje.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jlEstadoMasaje.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlEstadoMasaje.setForeground(new java.awt.Color(69, 54, 14));
        jlEstadoMasaje.setText("Estado:");

        jbCambiarEstadoMasaje.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbCambiarEstadoMasaje.setForeground(new java.awt.Color(69, 97, 11));
        jbCambiarEstadoMasaje.setText("Cambiar Estado");
        jbCambiarEstadoMasaje.setBorder(null);
        jbCambiarEstadoMasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarEstadoMasajeActionPerformed(evt);
            }
        });

        jbGuardarMasaje.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbGuardarMasaje.setForeground(new java.awt.Color(69, 97, 11));
        jbGuardarMasaje.setText("Guardar");
        jbGuardarMasaje.setBorder(null);
        jbGuardarMasaje.setPreferredSize(new java.awt.Dimension(42, 23));
        jbGuardarMasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarMasajeActionPerformed(evt);
            }
        });

        jbActualizarMasajes.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbActualizarMasajes.setForeground(new java.awt.Color(69, 97, 11));
        jbActualizarMasajes.setText("Actualizar");
        jbActualizarMasajes.setBorder(null);
        jbActualizarMasajes.setPreferredSize(new java.awt.Dimension(42, 23));
        jbActualizarMasajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarMasajesActionPerformed(evt);
            }
        });

        jbEliminarMasaje.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbEliminarMasaje.setForeground(new java.awt.Color(69, 97, 11));
        jbEliminarMasaje.setText("Eliminar");
        jbEliminarMasaje.setBorder(null);
        jbEliminarMasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarMasajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbGuardarMasaje, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jbActualizarMasajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbEliminarMasaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCambiarEstadoMasaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlDetalleMasaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfDetalleMasaje)
                            .addComponent(jtfNombreMasaje)
                            .addComponent(jtfDuracionMasaje)
                            .addComponent(jlDuracionMasaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbTipoDeMasaje, 0, 182, Short.MAX_VALUE)
                            .addComponent(jlNombreMasaje)
                            .addComponent(jlTipoDeMasaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCostoMasaje)
                            .addComponent(jtfCostoMasaje)
                            .addComponent(jcbEstadoMasaje, 0, 153, Short.MAX_VALUE)
                            .addComponent(jlEstadoMasaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbBuscarMasaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jlGestionMasajes)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionMasajes)
                .addGap(33, 33, 33)
                .addComponent(jlNombreMasaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBuscarMasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombreMasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlDetalleMasaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDetalleMasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCostoMasaje)
                    .addComponent(jlDuracionMasaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfCostoMasaje, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jtfDuracionMasaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlEstadoMasaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbEstadoMasaje))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTipoDeMasaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTipoDeMasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbGuardarMasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminarMasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCambiarEstadoMasaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbActualizarMasajes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDuracionMasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDuracionMasajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDuracionMasajeActionPerformed

    private void jbCambiarEstadoMasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarEstadoMasajeActionPerformed

    String nombre = jtfNombreMasaje.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre del masaje.");
        return;
    }

    Masaje m = masajeData.buscarMasajePorNombre(nombre);
    if (m == null) {
        JOptionPane.showMessageDialog(this, "No se encontro un masaje con ese nombre.");
        return;
    }

    boolean nuevoEstado = !m.isActivo();
    String estadoTexto = nuevoEstado ? "activo" : "inactivo";

    int confirmacion = JOptionPane.showConfirmDialog(this,
        "¿Desea cambiar el estado del masaje \"" + nombre + "\" a " + estadoTexto + "?",
        "Confirmar cambio de estado", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        masajeData.cambiarEstadoMasaje(nombre, nuevoEstado);
        jcbEstadoMasaje.setSelectedIndex(nuevoEstado ? 0 : 1);
        }
    }//GEN-LAST:event_jbCambiarEstadoMasajeActionPerformed

    private void jbGuardarMasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarMasajeActionPerformed
    if (!validarCampos()) {
        return;
    }

    try {
        String nombre = jtfNombreMasaje.getText().trim();
        String detalle = jtfDetalleMasaje.getText().trim();
        int duracion = Integer.parseInt(jtfDuracionMasaje.getText().trim());
        double costo = Double.parseDouble(jtfCostoMasaje.getText().trim());
        TipoMasaje tipo = (TipoMasaje) jcbTipoDeMasaje.getSelectedItem();
        boolean activo = jcbEstadoMasaje.getSelectedIndex() == 0;

        Masaje m = new Masaje(nombre, detalle, duracion, costo, activo, tipo);
        masajeData.insertarTratamiento(m);
        limpiarCampos();
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error inesperado al guardar: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbGuardarMasajeActionPerformed

    private void jbEliminarMasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarMasajeActionPerformed
        
    String nombre = jtfNombreMasaje.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre del masaje a eliminar.");
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(this,
        "¿Está seguro que desea eliminar el masaje \"" + nombre + "\" permanentemente?",
        "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        masajeData.eliminarMasajePorNombre(nombre);
        limpiarCampos();
    }
    }//GEN-LAST:event_jbEliminarMasajeActionPerformed

    private void jcbEstadoMasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoMasajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstadoMasajeActionPerformed

    private void jbBuscarMasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarMasajeActionPerformed

        String nombre = jtfNombreMasaje.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del masaje a buscar.");
            return;
        }

        Masaje m = masajeData.buscarMasajePorNombre(nombre);

        if (m != null) {
            jtfDetalleMasaje.setText(m.getDetalleTratamiento());
            jtfDuracionMasaje.setText(String.valueOf(m.getDuracionTratamiento()));
            jtfCostoMasaje.setText(String.valueOf(m.getCostoTratamiento()));
            jcbTipoDeMasaje.setSelectedItem(m.getTipo());
            jcbEstadoMasaje.setSelectedIndex(m.isActivo() ? 0 : 1);
            JOptionPane.showMessageDialog(this, "Masaje encontrado correctamente.");
        } else {
        
            limpiarCamposMenosNombre();
        }
    }//GEN-LAST:event_jbBuscarMasajeActionPerformed

    private void jbActualizarMasajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarMasajesActionPerformed
        if (!validarCampos()) {
            return;
        }

        String nombre = jtfNombreMasaje.getText().trim();
        Masaje existente = masajeData.buscarMasajePorNombre(nombre);
        if (existente == null) {
            JOptionPane.showMessageDialog(this, "No se encontro un masaje con ese nombre para actualizar.");
            return;
        }

        try {
            String detalle = jtfDetalleMasaje.getText().trim();
            int duracion = Integer.parseInt(jtfDuracionMasaje.getText().trim());
            double costo = Double.parseDouble(jtfCostoMasaje.getText().trim());
            TipoMasaje tipo = (TipoMasaje) jcbTipoDeMasaje.getSelectedItem();
            boolean activo = jcbEstadoMasaje.getSelectedIndex() == 0;

            existente.setDetalleTratamiento(detalle);
            existente.setDuracionTratamiento(duracion);
            existente.setCostoTratamiento(costo);
            existente.setTipo(tipo);
            existente.setActivo(activo);

            masajeData.modificarMasaje(existente);
            limpiarCampos();
        
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error inesperado al actualizar: " + ex.getMessage());
            }
    }//GEN-LAST:event_jbActualizarMasajesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbActualizarMasajes;
    private javax.swing.JButton jbBuscarMasaje;
    private javax.swing.JButton jbCambiarEstadoMasaje;
    private javax.swing.JButton jbEliminarMasaje;
    private javax.swing.JButton jbGuardarMasaje;
    private javax.swing.JComboBox<String> jcbEstadoMasaje;
    private javax.swing.JComboBox<Object> jcbTipoDeMasaje;
    private javax.swing.JLabel jlCostoMasaje;
    private javax.swing.JLabel jlDetalleMasaje;
    private javax.swing.JLabel jlDuracionMasaje;
    private javax.swing.JLabel jlEstadoMasaje;
    private javax.swing.JLabel jlGestionMasajes;
    private javax.swing.JLabel jlNombreMasaje;
    private javax.swing.JLabel jlTipoDeMasaje;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfCostoMasaje;
    private javax.swing.JTextField jtfDetalleMasaje;
    private javax.swing.JTextField jtfDuracionMasaje;
    private javax.swing.JTextField jtfNombreMasaje;
    // End of variables declaration//GEN-END:variables

    private void limpiarCamposMenosNombre() {
        jtfDetalleMasaje.setText("");
        jtfDuracionMasaje.setText("");
        jtfCostoMasaje.setText("");
        jcbEstadoMasaje.setSelectedIndex(0);
        jcbTipoDeMasaje.setSelectedIndex(0);
}

    private void limpiarCampos() {
        jtfNombreMasaje.setText("");
        jtfDetalleMasaje.setText("");
        jtfDuracionMasaje.setText("");
        jtfCostoMasaje.setText("");
        jcbEstadoMasaje.setSelectedIndex(0);
        jcbTipoDeMasaje.setSelectedIndex(0);
    }
    private boolean validarCampos() {
    StringBuilder errores = new StringBuilder();
    
    String nombre = jtfNombreMasaje.getText().trim();
    String detalle = jtfDetalleMasaje.getText().trim();
    String duracionStr = jtfDuracionMasaje.getText().trim();
    String costoStr = jtfCostoMasaje.getText().trim();

    if (nombre.isEmpty()) {
        errores.append("- El campo Nombre no puede estar vacío.\n");
    } else if (!nombre.matches("^[a-zA-Z]+$")) {
        errores.append("- El Nombre solo debe contener letras (sin espacios ni números).\n");
    }

    if (detalle.isEmpty()) {
        errores.append("- El campo Detalle no puede estar vacío.\n");
    } else if (!detalle.matches("^[a-zA-Z ]+$")) {
        errores.append("- El Detalle solo debe contener letras y espacios.\n");
    }

    if (duracionStr.isEmpty()) {
        errores.append("- El campo Duración no puede estar vacío.\n");
    } else if (!duracionStr.matches("^[0-9]+$")) {
        errores.append("- La Duración solo debe contener números enteros (ej. 60).\n");
    }

    if (costoStr.isEmpty()) {
        errores.append("- El campo Costo no puede estar vacío.\n");
    } else if (!costoStr.matches("^[0-9]+(\\.[0-9]+)?$")) {
        errores.append("- El Costo solo debe contener números (ej. 2500 o 2500.50).\n");
    }

    if (errores.length() > 0) {
        JOptionPane.showMessageDialog(this,
            "Por favor, corrija los siguientes errores:\n\n" + errores.toString(),
            "Error de Validación",
            JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
    }
}
