
package Vistass;

import Modeloo.Conexion;
import Modeloo.Sesion;
import Persistencia.SesionData;
import java.awt.HeadlessException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import org.mariadb.jdbc.Connection;

public class AgregarSesion extends javax.swing.JInternalFrame {

    private SesionData sd;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    private int codSesionActual = -1;
    private boolean estadoActual = false;
    
    public AgregarSesion() {
        initComponents();
        sd = new SesionData((Connection) Conexion.getConexion());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jtfFechaFin = new javax.swing.JTextField();
        jbBuscarSesion = new javax.swing.JButton();
        jtfCodTratamiento = new javax.swing.JTextField();
        jtfCodMasajista = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jlCodigoSesion = new javax.swing.JLabel();
        jlFechaFin = new javax.swing.JLabel();
        jlGestionClientes = new javax.swing.JLabel();
        jlCodTratamiento = new javax.swing.JLabel();
        jlCodMasajista = new javax.swing.JLabel();
        jtfFechaInicio = new javax.swing.JTextField();
        jtfCodDiaSpa = new javax.swing.JTextField();
        jlCodDiaSpa = new javax.swing.JLabel();
        jtfCodInstalacion = new javax.swing.JTextField();
        jlCodInstalacion = new javax.swing.JLabel();
        jlEstadoInstalacion = new javax.swing.JLabel();
        jcbEstadoInstalacion = new javax.swing.JComboBox<>();
        jbGuardarSesion = new javax.swing.JButton();
        jbActualizarSesion = new javax.swing.JButton();
        jbEliminarSesion = new javax.swing.JButton();
        jbCambiarEstadoSesion = new javax.swing.JButton();
        jlFechaInicio1 = new javax.swing.JLabel();
        jtfCodigoSesion = new javax.swing.JTextField();

        popupMenu1.setLabel("popupMenu1");

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);

        jtfFechaFin.setForeground(new java.awt.Color(69, 54, 14));
        jtfFechaFin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jbBuscarSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbBuscarSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbBuscarSesion.setText("Buscar");
        jbBuscarSesion.setBorder(null);
        jbBuscarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarSesionActionPerformed(evt);
            }
        });

        jtfCodTratamiento.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodTratamiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jtfCodMasajista.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodMasajista.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jlCodigoSesion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodigoSesion.setForeground(new java.awt.Color(69, 54, 14));
        jlCodigoSesion.setText("Codigo sesion:");

        jlFechaFin.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlFechaFin.setForeground(new java.awt.Color(69, 54, 14));
        jlFechaFin.setText("Fecha de finalizacion:");

        jlGestionClientes.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlGestionClientes.setForeground(new java.awt.Color(69, 97, 11));
        jlGestionClientes.setText("Gestion Sesiones");

        jlCodTratamiento.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodTratamiento.setForeground(new java.awt.Color(69, 54, 14));
        jlCodTratamiento.setText("Codigo tratamiento:");

        jlCodMasajista.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodMasajista.setForeground(new java.awt.Color(69, 54, 14));
        jlCodMasajista.setText("Codigo Masajista:");

        jtfFechaInicio.setForeground(new java.awt.Color(69, 54, 14));
        jtfFechaInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jtfCodDiaSpa.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodDiaSpa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jlCodDiaSpa.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodDiaSpa.setForeground(new java.awt.Color(69, 54, 14));
        jlCodDiaSpa.setText("Codigo Dia de Spa:");

        jtfCodInstalacion.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodInstalacion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jlCodInstalacion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodInstalacion.setForeground(new java.awt.Color(69, 54, 14));
        jlCodInstalacion.setText("Codigo Instalacion:");

        jlEstadoInstalacion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlEstadoInstalacion.setForeground(new java.awt.Color(69, 54, 14));
        jlEstadoInstalacion.setText("Estado:");

        jcbEstadoInstalacion.setBackground(new java.awt.Color(242, 242, 242));
        jcbEstadoInstalacion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jcbEstadoInstalacion.setForeground(new java.awt.Color(69, 97, 11));
        jcbEstadoInstalacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstadoInstalacion.setBorder(null);

        jbGuardarSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbGuardarSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbGuardarSesion.setText("Guardar");
        jbGuardarSesion.setBorder(null);
        jbGuardarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarSesionActionPerformed(evt);
            }
        });

        jbActualizarSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbActualizarSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbActualizarSesion.setText("Actualizar");
        jbActualizarSesion.setBorder(null);
        jbActualizarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarSesionActionPerformed(evt);
            }
        });

        jbEliminarSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbEliminarSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbEliminarSesion.setText("Eliminar");
        jbEliminarSesion.setBorder(null);
        jbEliminarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarSesionActionPerformed(evt);
            }
        });

        jbCambiarEstadoSesion.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbCambiarEstadoSesion.setForeground(new java.awt.Color(69, 97, 11));
        jbCambiarEstadoSesion.setText("Cambiar Estado");
        jbCambiarEstadoSesion.setBorder(null);
        jbCambiarEstadoSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarEstadoSesionActionPerformed(evt);
            }
        });

        jlFechaInicio1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlFechaInicio1.setForeground(new java.awt.Color(69, 54, 14));
        jlFechaInicio1.setText("Fecha de incio:");

        jtfCodigoSesion.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodigoSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlGestionClientes)
                                .addGap(74, 74, 74))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlCodigoSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCodigoSesion, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(54, 54, 54)
                                .addComponent(jbBuscarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlCodInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfCodInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfCodDiaSpa, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlCodDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jlEstadoInstalacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcbEstadoInstalacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfFechaInicio)
                                    .addComponent(jlFechaInicio1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jtfCodTratamiento)
                                    .addComponent(jlCodTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfFechaFin)
                                    .addComponent(jlCodMasajista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfCodMasajista)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbGuardarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbActualizarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbCambiarEstadoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbEliminarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlCodigoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCodigoSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlFechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jtfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlFechaFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCodTratamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfCodTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodDiaSpa)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jtfCodDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCodInstalacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCodInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCodMasajista)
                        .addGap(13, 13, 13)
                        .addComponent(jtfCodMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEstadoInstalacion)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jcbEstadoInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCambiarEstadoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarSesionActionPerformed

        if (!validarCampos()) {
            return;
        }

        try {
            int codTratamiento = Integer.parseInt(jtfCodTratamiento.getText());
            int codMasajista = Integer.parseInt(jtfCodMasajista.getText());
            int codInstalacion = Integer.parseInt(jtfCodInstalacion.getText());
            int codPack = Integer.parseInt(jtfCodDiaSpa.getText());
            boolean estado = jcbEstadoInstalacion.getSelectedItem().toString().equalsIgnoreCase("Activo");

            LocalDateTime fechaInicio = LocalDateTime.parse(jtfFechaInicio.getText(), formatter);
            LocalDateTime fechaFin = LocalDateTime.parse(jtfFechaFin.getText(), formatter);

            Sesion s = new Sesion();
            s.setCodTratamiento(codTratamiento);
            s.setCodMasajista(codMasajista);
            s.setCodInstal(codInstalacion);
            s.setCodPack(codPack);
            s.setFechaInicio(fechaInicio);
            s.setFechaFin(fechaFin);
            s.setEstadoInstalacion(estado);

            sd.insertarSesion(s);

            JOptionPane.showMessageDialog(this, "La sesion se guardo correctamente.");
            limpiarCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los codigos tienen que ser numericos.");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar la sesion: " + e.getMessage());
        }
    }//GEN-LAST:event_jbGuardarSesionActionPerformed

    private void jbActualizarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarSesionActionPerformed
        if (this.codSesionActual <= 0) {
            JOptionPane.showMessageDialog(this, "Debes buscar una sesion antes.");
            return;
        }
        
        if (!validarCampos()) {
            return;
        }

        try {
            int codTratamiento = Integer.parseInt(jtfCodTratamiento.getText());
            int codMasajista = Integer.parseInt(jtfCodMasajista.getText());
            int codInstalacion = Integer.parseInt(jtfCodInstalacion.getText());
            int codPack = Integer.parseInt(jtfCodDiaSpa.getText());
            boolean estado = jcbEstadoInstalacion.getSelectedItem().toString().equalsIgnoreCase("Activo");

            LocalDateTime fechaInicio = LocalDateTime.parse(jtfFechaInicio.getText(), formatter);
            LocalDateTime fechaFin = LocalDateTime.parse(jtfFechaFin.getText(), formatter);

            Sesion s = new Sesion(this.codSesionActual, fechaInicio, fechaFin, codTratamiento, codMasajista, codPack, codInstalacion, estado); //

            if (sd.actualizarSesion(s)) { 
                JOptionPane.showMessageDialog(this, "La sesion fue actualizada correctamente.");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la sesion.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El codigo debe ser numerico.");
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato de la fecha (dd/MM/yyyy HH:mm).");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar la sesion: " + e.getMessage());
        }
    }//GEN-LAST:event_jbActualizarSesionActionPerformed

    private void jbEliminarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarSesionActionPerformed
         if (this.codSesionActual <= 0) {
            JOptionPane.showMessageDialog(this, "Debes buscar una sesion antes.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, 
                "¿Estas seguro de eliminar esta sesion?", 
                "Confirmar eliminacion", 
                JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            try {
                if (sd.eliminarSesion(this.codSesionActual)) { //
                    JOptionPane.showMessageDialog(this, "La sesion fue eliminada correctamente.");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar la sesion.");
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar la sesion: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jbEliminarSesionActionPerformed

    private void jbCambiarEstadoSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarEstadoSesionActionPerformed
        if (this.codSesionActual <= 0) {
            JOptionPane.showMessageDialog(this, "Debes buscar una sesion antes.");
            return;
        }

        try {
            boolean nuevoEstado = !this.estadoActual;

            if (sd.BajaAltaLogicaSesion(this.codSesionActual, nuevoEstado)) {
                
                String estadoStr = nuevoEstado ? "Activo" : "Inactivo";
                JOptionPane.showMessageDialog(this, "El estado de la instalacion se actualizo a: " + estadoStr);

                this.estadoActual = nuevoEstado;
                
                jcbEstadoInstalacion.setSelectedItem(nuevoEstado ? "Activo" : "Inactivo");           

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo cambiar el estado de la sesion.");
            }
            
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al cambiar el estado: " + e.getMessage());
        }
    }//GEN-LAST:event_jbCambiarEstadoSesionActionPerformed

    private void jbBuscarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarSesionActionPerformed
        try {
            int codSesion = Integer.parseInt(jtfCodigoSesion.getText());
            Sesion sesion = sd.buscarSesion(codSesion);

            if (sesion != null) {
                this.codSesionActual = sesion.getCodSesion();
                this.estadoActual = sesion.isEstadoInstalacion();

                jtfFechaInicio.setText(sesion.getFechaInicio().format(formatter));
                jtfFechaFin.setText(sesion.getFechaFin().format(formatter));
                jtfCodTratamiento.setText(String.valueOf(sesion.getCodTratamiento()));
                jtfCodMasajista.setText(String.valueOf(sesion.getCodMasajista()));
                jtfCodDiaSpa.setText(String.valueOf(sesion.getCodPack()));
                jtfCodInstalacion.setText(String.valueOf(sesion.getCodInstal()));
                jcbEstadoInstalacion.setSelectedItem(sesion.isEstadoInstalacion() ? "Activo" : "Inactivo");

            } else {
                JOptionPane.showMessageDialog(this, "No se encontro ninguna sesion con este codigo.");
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El codigo debe ser numerico.");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar la sesion: " + e.getMessage());
        }
    }//GEN-LAST:event_jbBuscarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbActualizarSesion;
    private javax.swing.JButton jbBuscarSesion;
    private javax.swing.JButton jbCambiarEstadoSesion;
    private javax.swing.JButton jbEliminarSesion;
    private javax.swing.JButton jbGuardarSesion;
    private javax.swing.JComboBox<String> jcbEstadoInstalacion;
    private javax.swing.JLabel jlCodDiaSpa;
    private javax.swing.JLabel jlCodInstalacion;
    private javax.swing.JLabel jlCodMasajista;
    private javax.swing.JLabel jlCodTratamiento;
    private javax.swing.JLabel jlCodigoSesion;
    private javax.swing.JLabel jlEstadoInstalacion;
    private javax.swing.JLabel jlFechaFin;
    private javax.swing.JLabel jlFechaInicio1;
    private javax.swing.JLabel jlGestionClientes;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfCodDiaSpa;
    private javax.swing.JTextField jtfCodInstalacion;
    private javax.swing.JTextField jtfCodMasajista;
    private javax.swing.JTextField jtfCodTratamiento;
    private javax.swing.JTextField jtfCodigoSesion;
    private javax.swing.JTextField jtfFechaFin;
    private javax.swing.JTextField jtfFechaInicio;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        jtfCodigoSesion.setText("");
        jtfFechaInicio.setText("");
        jtfFechaFin.setText("");
        jtfCodTratamiento.setText("");
        jtfCodMasajista.setText("");
        jtfCodInstalacion.setText("");
        jtfCodDiaSpa.setText("");
        jcbEstadoInstalacion.setSelectedIndex(0);
        this.codSesionActual = -1;
        this.estadoActual = false;
    }

    private boolean validarCampos() {
        
    StringBuilder errores = new StringBuilder();
    
    String fechaInicioStr = jtfFechaInicio.getText().trim();
    String fechaFinStr = jtfFechaFin.getText().trim();
    String codTrat = jtfCodTratamiento.getText().trim();
    String codMas = jtfCodMasajista.getText().trim();
    String codInst = jtfCodInstalacion.getText().trim();
    String codDia = jtfCodDiaSpa.getText().trim(); 

    try {
        LocalDateTime.parse(fechaInicioStr, formatter);
    } catch (DateTimeParseException e) {
        errores.append("- El formato de Fecha de Inicio es incorrecto (use dd/MM/yyyy HH:mm).\n");
    }
    
    try {
        LocalDateTime.parse(fechaFinStr, formatter);
    } catch (DateTimeParseException e) {
        errores.append("- El formato de Fecha de Finalización es incorrecto (use dd/MM/yyyy HH:mm).\n");
    }

    if (codTrat.isEmpty()) {
        errores.append("- El Código de Tratamiento no puede estar vacío.\n");
    } else if (!codTrat.matches("^[0-9]+$")) { 
        errores.append("- El Código de Tratamiento solo debe contener números.\n");
    }

    if (codMas.isEmpty()) {
        errores.append("- El Código de Masajista no puede estar vacío.\n");
    } else if (!codMas.matches("^[0-9]+$")) {
        errores.append("- El Código de Masajista solo debe contener números.\n");
    }

    if (codInst.isEmpty()) {
        errores.append("- El Código de Instalación no puede estar vacío.\n");
    } else if (!codInst.matches("^[0-9]+$")) {
        errores.append("- El Código de Instalación solo debe contener números.\n");
    }

    if (codDia.isEmpty()) {
        errores.append("- El Código de Día de Spa no puede estar vacío.\n");
    } else if (!codDia.matches("^[0-9]+$")) {
        errores.append("- El Código de Día de Spa solo debe contener números.\n");
    }

    if (errores.length() > 0) {
        JOptionPane.showMessageDialog(this, 
            "Por favor, corrija los siguientes errores:\n\n" + errores.toString(), 
            "Error de Validación", 
            JOptionPane.ERROR_MESSAGE);
        return false; 
    }

    return true;
    }
}
