
package Vistass;

public class AgregarMasajista extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarMasajista
     */
    public AgregarMasajista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNombreMasajista = new javax.swing.JTextField();
        jcbEspecialidadMasajista = new javax.swing.JComboBox<>();
        jcbEstadoMasajista = new javax.swing.JComboBox<>();
        jbBuscarMasajista = new javax.swing.JButton();
        jtfTelefonoMasajista = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jbGuardarMasajista = new javax.swing.JButton();
        jlMatriculaMasajista = new javax.swing.JLabel();
        jbActualizarMasajista = new javax.swing.JButton();
        jlNombreMasajista = new javax.swing.JLabel();
        jbEliminarMasajista = new javax.swing.JButton();
        jlGestionMasajista = new javax.swing.JLabel();
        jbCambiarEstadoMasajista = new javax.swing.JButton();
        jlTelefonoMasajista = new javax.swing.JLabel();
        jlEspecialidadMasajista = new javax.swing.JLabel();
        jtfMatriculaMasajista = new javax.swing.JTextField();
        jlEstadoMasajista = new javax.swing.JLabel();

        jcbEspecialidadMasajista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facial", "Corporal", "Relajacion", "Estetico" }));

        jcbEstadoMasajista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jbBuscarMasajista.setText("Buscar");

        jtfTelefonoMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefonoMasajistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setText("Spa Entre Dedos");

        jbGuardarMasajista.setText("Guardar");
        jbGuardarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarMasajistaActionPerformed(evt);
            }
        });

        jlMatriculaMasajista.setText("Matricula:");

        jbActualizarMasajista.setText("Actualizar");

        jlNombreMasajista.setText("Nombre Completo:");

        jbEliminarMasajista.setText("Eliminar");

        jlGestionMasajista.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jlGestionMasajista.setText("Gestion Masajistas");

        jbCambiarEstadoMasajista.setText("Cambiar Estado");

        jlTelefonoMasajista.setText("Telefono:");

        jlEspecialidadMasajista.setText("Especialidad:");

        jlEstadoMasajista.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jlGestionMasajista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNombreMasajista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jtfNombreMasajista)
                            .addComponent(jtfMatriculaMasajista)
                            .addComponent(jtfTelefonoMasajista)
                            .addComponent(jlTelefonoMasajista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlEspecialidadMasajista)
                            .addComponent(jlEstadoMasajista)
                            .addComponent(jcbEspecialidadMasajista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbEstadoMasajista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlMatriculaMasajista))
                        .addGap(49, 49, 49)
                        .addComponent(jbBuscarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbGuardarMasajista)
                        .addGap(18, 18, 18)
                        .addComponent(jbActualizarMasajista)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminarMasajista)
                        .addGap(18, 18, 18)
                        .addComponent(jbCambiarEstadoMasajista)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jlGestionMasajista)
                .addGap(37, 37, 37)
                .addComponent(jlMatriculaMasajista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMatriculaMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarMasajista))
                .addGap(27, 27, 27)
                .addComponent(jlNombreMasajista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNombreMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlTelefonoMasajista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTelefonoMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlEspecialidadMasajista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbEspecialidadMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlEstadoMasajista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbEstadoMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarMasajista)
                    .addComponent(jbEliminarMasajista)
                    .addComponent(jbActualizarMasajista)
                    .addComponent(jbCambiarEstadoMasajista))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTelefonoMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefonoMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefonoMasajistaActionPerformed

    private void jbGuardarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGuardarMasajistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbActualizarMasajista;
    private javax.swing.JButton jbBuscarMasajista;
    private javax.swing.JButton jbCambiarEstadoMasajista;
    private javax.swing.JButton jbEliminarMasajista;
    private javax.swing.JButton jbGuardarMasajista;
    private javax.swing.JComboBox<String> jcbEspecialidadMasajista;
    private javax.swing.JComboBox<String> jcbEstadoMasajista;
    private javax.swing.JLabel jlEspecialidadMasajista;
    private javax.swing.JLabel jlEstadoMasajista;
    private javax.swing.JLabel jlGestionMasajista;
    private javax.swing.JLabel jlMatriculaMasajista;
    private javax.swing.JLabel jlNombreMasajista;
    private javax.swing.JLabel jlTelefonoMasajista;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfDuracionMasaje;
    private javax.swing.JTextField jtfMatriculaMasajista;
    private javax.swing.JTextField jtfNombreMasajista;
    private javax.swing.JTextField jtfTelefonoMasajista;
    // End of variables declaration//GEN-END:variables
}
