/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistass;

import Modeloo.Cliente;
import Modeloo.Conexion;
import Modeloo.DiaSpa;
import Persistencia.ClienteData;
import Persistencia.DiaSpaData;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import org.mariadb.jdbc.Connection;

/**
 *
 * @author alybe
 */
public class AgregarDiaSpa extends javax.swing.JInternalFrame {

    private DiaSpaData dsData;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    
    public AgregarDiaSpa() {
        initComponents();
        dsData = new DiaSpaData((Connection) Conexion.getConexion());
        jcbEstadoDiaSpa.addItem("Activo");
        jcbEstadoDiaSpa.addItem("Inactivo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCodCli = new javax.swing.JLabel();
        jbEliminarDiaSpa = new javax.swing.JButton();
        jlFechaYHora = new javax.swing.JLabel();
        jbCambiarEstadoDiaSpa = new javax.swing.JButton();
        jlGestionDiaSpa = new javax.swing.JLabel();
        jlPreferencias = new javax.swing.JLabel();
        jlEstadoDiaSpa = new javax.swing.JLabel();
        jlMonto = new javax.swing.JLabel();
        jtfCodCli = new javax.swing.JTextField();
        jcbEstadoDiaSpa = new javax.swing.JComboBox<>();
        jtfFechaYHora = new javax.swing.JTextField();
        jbBuscarDiaSpa = new javax.swing.JButton();
        jtfPreferencias = new javax.swing.JTextField();
        jtfMonto = new javax.swing.JTextField();
        jbGuardarDiaSpa = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jbActualizarDiaSpa = new javax.swing.JButton();

        jlCodCli.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlCodCli.setForeground(new java.awt.Color(69, 54, 14));
        jlCodCli.setText("Codigo cliente:");

        jbEliminarDiaSpa.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbEliminarDiaSpa.setForeground(new java.awt.Color(69, 97, 11));
        jbEliminarDiaSpa.setText("Eliminar");
        jbEliminarDiaSpa.setBorder(null);
        jbEliminarDiaSpa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEliminarDiaSpa.setMaximumSize(new java.awt.Dimension(46, 26));
        jbEliminarDiaSpa.setMinimumSize(new java.awt.Dimension(40, 20));
        jbEliminarDiaSpa.setPreferredSize(new java.awt.Dimension(42, 23));
        jbEliminarDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarDiaSpaActionPerformed(evt);
            }
        });

        jlFechaYHora.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlFechaYHora.setForeground(new java.awt.Color(69, 54, 14));
        jlFechaYHora.setText("Fecha y hora:");

        jbCambiarEstadoDiaSpa.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbCambiarEstadoDiaSpa.setForeground(new java.awt.Color(69, 97, 11));
        jbCambiarEstadoDiaSpa.setText("Cambiar Estado");
        jbCambiarEstadoDiaSpa.setBorder(null);
        jbCambiarEstadoDiaSpa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCambiarEstadoDiaSpa.setMaximumSize(new java.awt.Dimension(46, 26));
        jbCambiarEstadoDiaSpa.setMinimumSize(new java.awt.Dimension(40, 20));
        jbCambiarEstadoDiaSpa.setPreferredSize(new java.awt.Dimension(42, 23));
        jbCambiarEstadoDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarEstadoDiaSpaActionPerformed(evt);
            }
        });

        jlGestionDiaSpa.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlGestionDiaSpa.setForeground(new java.awt.Color(69, 97, 11));
        jlGestionDiaSpa.setText("Gestion Dias de Spa");

        jlPreferencias.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlPreferencias.setForeground(new java.awt.Color(69, 54, 14));
        jlPreferencias.setText("Preferencias:");

        jlEstadoDiaSpa.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlEstadoDiaSpa.setForeground(new java.awt.Color(69, 54, 14));
        jlEstadoDiaSpa.setText("Estado:");
        jlEstadoDiaSpa.setToolTipText("");

        jlMonto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlMonto.setForeground(new java.awt.Color(69, 54, 14));
        jlMonto.setText("Monto:");

        jtfCodCli.setBackground(new java.awt.Color(242, 242, 242));
        jtfCodCli.setForeground(new java.awt.Color(69, 54, 14));
        jtfCodCli.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jcbEstadoDiaSpa.setBackground(new java.awt.Color(242, 242, 242));
        jcbEstadoDiaSpa.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jcbEstadoDiaSpa.setForeground(new java.awt.Color(69, 97, 11));
        jcbEstadoDiaSpa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstadoDiaSpa.setBorder(null);
        jcbEstadoDiaSpa.setPreferredSize(new java.awt.Dimension(76, 23));

        jtfFechaYHora.setBackground(new java.awt.Color(242, 242, 242));
        jtfFechaYHora.setForeground(new java.awt.Color(69, 54, 14));
        jtfFechaYHora.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));

        jbBuscarDiaSpa.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbBuscarDiaSpa.setForeground(new java.awt.Color(69, 97, 11));
        jbBuscarDiaSpa.setText("Buscar");
        jbBuscarDiaSpa.setBorder(null);
        jbBuscarDiaSpa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbBuscarDiaSpa.setMargin(null);
        jbBuscarDiaSpa.setMaximumSize(new java.awt.Dimension(46, 26));
        jbBuscarDiaSpa.setPreferredSize(new java.awt.Dimension(42, 24));
        jbBuscarDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarDiaSpaActionPerformed(evt);
            }
        });

        jtfPreferencias.setBackground(new java.awt.Color(242, 242, 242));
        jtfPreferencias.setForeground(new java.awt.Color(69, 54, 14));
        jtfPreferencias.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));
        jtfPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPreferenciasActionPerformed(evt);
            }
        });

        jtfMonto.setBackground(new java.awt.Color(242, 242, 242));
        jtfMonto.setForeground(new java.awt.Color(69, 54, 14));
        jtfMonto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(138, 186, 40)));
        jtfMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMontoActionPerformed(evt);
            }
        });

        jbGuardarDiaSpa.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbGuardarDiaSpa.setForeground(new java.awt.Color(69, 97, 11));
        jbGuardarDiaSpa.setText("Guardar");
        jbGuardarDiaSpa.setBorder(null);
        jbGuardarDiaSpa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbGuardarDiaSpa.setMaximumSize(new java.awt.Dimension(46, 26));
        jbGuardarDiaSpa.setMinimumSize(new java.awt.Dimension(40, 20));
        jbGuardarDiaSpa.setPreferredSize(new java.awt.Dimension(42, 23));
        jbGuardarDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarDiaSpaActionPerformed(evt);
            }
        });

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jbActualizarDiaSpa.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jbActualizarDiaSpa.setForeground(new java.awt.Color(69, 97, 11));
        jbActualizarDiaSpa.setText("Actualizar");
        jbActualizarDiaSpa.setBorder(null);
        jbActualizarDiaSpa.setMaximumSize(new java.awt.Dimension(4626, 4626));
        jbActualizarDiaSpa.setMinimumSize(new java.awt.Dimension(4020, 4020));
        jbActualizarDiaSpa.setPreferredSize(new java.awt.Dimension(42, 23));
        jbActualizarDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarDiaSpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCodCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlFechaYHora, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jtfCodCli)
                            .addComponent(jtfFechaYHora)
                            .addComponent(jtfPreferencias)
                            .addComponent(jlPreferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbGuardarDiaSpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbActualizarDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbEstadoDiaSpa, 0, 145, Short.MAX_VALUE)
                            .addComponent(jlEstadoDiaSpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfMonto)
                            .addComponent(jbBuscarDiaSpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEliminarDiaSpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCambiarEstadoDiaSpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jlTitulo)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGestionDiaSpa)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionDiaSpa)
                .addGap(37, 37, 37)
                .addComponent(jlCodCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscarDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlFechaYHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfFechaYHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jlPreferencias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlEstadoDiaSpa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbEstadoDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminarDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizarDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCambiarEstadoDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEliminarDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarDiaSpaActionPerformed

        try {
        int codCli = Integer.parseInt(jtfCodCli.getText());

        int opcion = JOptionPane.showConfirmDialog(this, 
            "¿Seguro que queres eliminar el dia de spa de este cliente?", 
            "Confirmar eliminacion", 
            JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            dsData.eliminarDiaSpaPorCliente(codCli);
            limpiarCampos();
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un codigo de cliente valido.");
    }
    }//GEN-LAST:event_jbEliminarDiaSpaActionPerformed

    private void jbCambiarEstadoDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarEstadoDiaSpaActionPerformed

        try {
        int codCli = Integer.parseInt(jtfCodCli.getText());
        boolean nuevoEstado = jcbEstadoDiaSpa.getSelectedItem().equals("Activo") ? false : true;
        dsData.cambiarEstadoDia(codCli, nuevoEstado);

        JOptionPane.showMessageDialog(this, "Estado cambiado correctamente.");
        limpiarCampos();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cambiar estado: " + e.getMessage());
    }
    }//GEN-LAST:event_jbCambiarEstadoDiaSpaActionPerformed

    private void jbBuscarDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarDiaSpaActionPerformed

        try {
            int codCli = Integer.parseInt(jtfCodCli.getText());
            DiaSpa dia = dsData.buscarDiaSpaPorCliente(codCli);
            
            if (dia != null) {
                if (dia.getFechaYHora() != null) {
                    jtfFechaYHora.setText(dia.getFechaYHora().format(formatter));
                } else {
                    jtfFechaYHora.setText("");
                }
                    jtfPreferencias.setText(dia.getPreferencias());
                    jtfMonto.setText(String.valueOf(dia.getMonto()));
                    jcbEstadoDiaSpa.setSelectedItem(dia.isEstadoDia() ? "Activo" : "Inactivo");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro un dia de spa para este cliente.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar el dia de spa: " + e.getMessage());
        }
    }//GEN-LAST:event_jbBuscarDiaSpaActionPerformed

    private void jtfPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPreferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPreferenciasActionPerformed

    private void jtfMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMontoActionPerformed

    private void jbGuardarDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarDiaSpaActionPerformed

        if (!validarCampos()) {
        JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
        return;
    }

    try {
        LocalDateTime fechaHora = LocalDateTime.parse(jtfFechaYHora.getText(), formatter);
        int codCliente = Integer.parseInt(jtfCodCli.getText());
        String preferencias = jtfPreferencias.getText();
        double monto = Double.parseDouble(jtfMonto.getText());
        boolean estado = jcbEstadoDiaSpa.getSelectedItem().equals("Activo");

        ClienteData cd = new ClienteData((Connection) Conexion.getConexion());
        Cliente cliente = cd.buscarCliente(codCliente);

        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "No se encontro un cliente con este codigo.");
            return;
        }

        if (cliente.isEstadoCliente() != estado) {
            JOptionPane.showMessageDialog(this, "El estado del cliente no coincide con el del dia.");
            return;
        }

        DiaSpa dia = new DiaSpa(fechaHora, preferencias, cliente, monto, estado);
        dsData.insertarDia(dia);

        JOptionPane.showMessageDialog(this, "El dia de spa fue guardado correctamente.");
        limpiarCampos();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }
    }//GEN-LAST:event_jbGuardarDiaSpaActionPerformed

    private void jbActualizarDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarDiaSpaActionPerformed

        if (!validarCampos()) {
        JOptionPane.showMessageDialog(this, "Debes completar todos los campos.");
        return;
    }

    try {
        int codCli = Integer.parseInt(jtfCodCli.getText());
        LocalDateTime fechaHora = LocalDateTime.parse(jtfFechaYHora.getText(), formatter);
        String preferencias = jtfPreferencias.getText();
        double monto = Double.parseDouble(jtfMonto.getText());
        boolean estado = jcbEstadoDiaSpa.getSelectedItem().equals("Activo");

        ClienteData cd = new ClienteData((Connection) Conexion.getConexion());
        Cliente cliente = cd.buscarCliente(codCli);

        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "No se encontro un cliente con este codigo.");
            return;
        }
        
        if (cliente.isEstadoCliente() != estado) {
            JOptionPane.showMessageDialog(this, "El estado del cliente no coincide con el del día de spa.");
            return;
        }

        DiaSpa dia = new DiaSpa(0, fechaHora, preferencias, cliente, monto, estado);
        if (dsData.actualizarDiaSpa(dia)) {
            JOptionPane.showMessageDialog(this, "El dia de spa fue actualizado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el dia.");
        }

        limpiarCampos();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_jbActualizarDiaSpaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbActualizarDiaSpa;
    private javax.swing.JButton jbBuscarDiaSpa;
    private javax.swing.JButton jbCambiarEstadoDiaSpa;
    private javax.swing.JButton jbEliminarDiaSpa;
    private javax.swing.JButton jbGuardarDiaSpa;
    private javax.swing.JComboBox<String> jcbEstadoDiaSpa;
    private javax.swing.JLabel jlCodCli;
    private javax.swing.JLabel jlEstadoDiaSpa;
    private javax.swing.JLabel jlFechaYHora;
    private javax.swing.JLabel jlGestionDiaSpa;
    private javax.swing.JLabel jlMonto;
    private javax.swing.JLabel jlPreferencias;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfCodCli;
    private javax.swing.JTextField jtfFechaYHora;
    private javax.swing.JTextField jtfMonto;
    private javax.swing.JTextField jtfPreferencias;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        jtfCodCli.setText("");
        jtfFechaYHora.setText("");
        jtfPreferencias.setText("");
        jtfMonto.setText("");
        jcbEstadoDiaSpa.setSelectedIndex(0);
    }

    private boolean validarCampos() {
       return !(jtfCodCli.getText().isEmpty() ||
             jtfFechaYHora.getText().isEmpty() ||
             jtfPreferencias.getText().isEmpty() ||
             jtfMonto.getText().isEmpty()); 
    }
}
