
package Vistass;

import Modeloo.Cliente;
import Modeloo.Conexion;
import Persistencia.ClienteData;
import javax.swing.JOptionPane;
import org.mariadb.jdbc.Connection;

public class AgregarCliente extends javax.swing.JInternalFrame {
    
    private Connection con;
    private ClienteData clienteData;
    private Cliente clienteEncontrado= null;
    
    public AgregarCliente() {
        initComponents();
        con = (Connection) Conexion.getConexion();
        clienteData = new ClienteData (con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlDniCliente = new javax.swing.JLabel();
        jlNombreCliente = new javax.swing.JLabel();
        jlGestionClientes = new javax.swing.JLabel();
        jlTelefonoCliente = new javax.swing.JLabel();
        jlEdadCliente = new javax.swing.JLabel();
        jtfDniCliente = new javax.swing.JTextField();
        jtfNombreCliente = new javax.swing.JTextField();
        jtfTelefonoCliente = new javax.swing.JTextField();
        jtfEdadCliente = new javax.swing.JTextField();
        jbGuardarCliente = new javax.swing.JButton();
        jbActualizarCliente = new javax.swing.JButton();
        jbEliminarCliente = new javax.swing.JButton();
        jbCambiarEstadoCliente = new javax.swing.JButton();
        jlAfeccionesCliente = new javax.swing.JLabel();
        jlEstadoCliente = new javax.swing.JLabel();
        jcbAfeccionesCliente = new javax.swing.JComboBox<>();
        jcbEstadoCliente = new javax.swing.JComboBox<>();
        jbBuscarCliente = new javax.swing.JButton();

        setClosable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setText("Spa Entre Dedos");

        jlDniCliente.setText("Dni:");

        jlNombreCliente.setText("Nombre Completo:");

        jlGestionClientes.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jlGestionClientes.setText("Gestion Clientes");

        jlTelefonoCliente.setText("Telefono:");

        jlEdadCliente.setText("Edad:");

        jtfTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefonoClienteActionPerformed(evt);
            }
        });

        jbGuardarCliente.setText("Guardar");
        jbGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarClienteActionPerformed(evt);
            }
        });

        jbActualizarCliente.setText("Actualizar");
        jbActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarClienteActionPerformed(evt);
            }
        });

        jbEliminarCliente.setText("Eliminar");
        jbEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarClienteActionPerformed(evt);
            }
        });

        jbCambiarEstadoCliente.setText("Cambiar Estado");
        jbCambiarEstadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarEstadoClienteActionPerformed(evt);
            }
        });

        jlAfeccionesCliente.setText("Tiene afecciones?");

        jlEstadoCliente.setText("Estado:");

        jcbAfeccionesCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jcbEstadoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jbBuscarCliente.setText("Buscar");
        jbBuscarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 186, 40)));
        jbBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbBuscarCliente.setMargin(null);
        jbBuscarCliente.setMaximumSize(new java.awt.Dimension(46, 26));
        jbBuscarCliente.setPreferredSize(new java.awt.Dimension(42, 24));
        jbBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jlGestionClientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNombreCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jtfNombreCliente)
                            .addComponent(jtfDniCliente)
                            .addComponent(jtfTelefonoCliente)
                            .addComponent(jlEdadCliente)
                            .addComponent(jtfEdadCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlTelefonoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlAfeccionesCliente)
                            .addComponent(jlEstadoCliente)
                            .addComponent(jcbAfeccionesCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbEstadoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(jbBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(jbGuardarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jbActualizarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jbCambiarEstadoCliente)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionClientes)
                .addGap(37, 37, 37)
                .addComponent(jlDniCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jlNombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlTelefonoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlEdadCliente)
                .addGap(10, 10, 10)
                .addComponent(jtfEdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlAfeccionesCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbAfeccionesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlEstadoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbEstadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarCliente)
                    .addComponent(jbEliminarCliente)
                    .addComponent(jbActualizarCliente)
                    .addComponent(jbCambiarEstadoCliente))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefonoClienteActionPerformed

    private void jbGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarClienteActionPerformed
        //ESTE YA FUNCIONA
        try{
            if(jtfDniCliente.getText().isEmpty() || jtfNombreCliente.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Los campos DNI y Nombre no pueden estar vacios");
                return;
            }
            String dni = jtfDniCliente.getText();
            String nombre = jtfNombreCliente.getText();
            String telefono = jtfTelefonoCliente.getText();
            int edad = Integer.parseInt(jtfEdadCliente.getText());
            
            boolean afecciones = jcbAfeccionesCliente.getSelectedItem().toString().equals("Si");
            boolean estado = jcbEstadoCliente.getSelectedItem().toString().equals("Activo");
            
            Cliente nuevoCliente = new Cliente(dni,nombre,telefono,edad,afecciones,estado);
            
            if (clienteData.guardarCliente(nuevoCliente)){
                JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente");
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo guardar cliente", "Error", JOptionPane.ERROR_MESSAGE);
            }
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "El campo 'edad' debe ser un numero ");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al guardar" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbGuardarClienteActionPerformed

    private void jbBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarClienteActionPerformed
        //ESTE TAMBIÉN FUNCIONA
        try {
        String dni = jtfDniCliente.getText();
        
        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo DNI no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        clienteEncontrado = clienteData.buscarClientePorDni(dni);

        if (clienteEncontrado != null) {
            jtfNombreCliente.setText(clienteEncontrado.getNombreCliente());
            jtfTelefonoCliente.setText(clienteEncontrado.getTelefonoCliente());
            jtfEdadCliente.setText(String.valueOf(clienteEncontrado.getEdad()));

            jcbAfeccionesCliente.setSelectedItem(clienteEncontrado.isAfecciones() ? "Si" : "No");
            
            jcbEstadoCliente.setSelectedItem(clienteEncontrado.isEstadoCliente() ? "Activo" : "Inactivo");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún cliente con ese DNI.", "Búsqueda fallida", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposMenosDni();
            clienteEncontrado = null;
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al buscar.", "Error", JOptionPane.ERROR_MESSAGE);
            clienteEncontrado = null;
        }
    }//GEN-LAST:event_jbBuscarClienteActionPerformed

    private void jbActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarClienteActionPerformed
        //ESTO HAY QUE CORREGIRLO POR QUE TIRA TE DEJA ACTUALIZARLO PERO SALE LOS DOS CARTELES EL DE ACTUALIZADO CORRECTAMENTE Y EL DE NO SE PUDO ACTUALIZAR EL CLIENTE
        //(AUNQUE SI FUNCIONA Y SI ACTUALIZA EL CLIENTE)
        if(clienteEncontrado == null){
            JOptionPane.showMessageDialog(this, "Debe buscar un cliente antes de poder actualizar","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            String dni = jtfDniCliente.getText();
            String nombre = jtfNombreCliente.getText();
            String telefono = jtfTelefonoCliente.getText();
            int edad = Integer.parseInt(jtfEdadCliente.getText());
            boolean afecciones = jcbAfeccionesCliente.getSelectedItem().toString().equals("Si");
            boolean estado = jcbEstadoCliente.getSelectedItem().toString().equals("Activo");
            
            clienteEncontrado.setDni(dni);
            clienteEncontrado.setNombreCliente(nombre);
            clienteEncontrado.setTelefonoCliente(telefono);
            clienteEncontrado.setEdad(edad);
            clienteEncontrado.setAfecciones(afecciones);
            clienteEncontrado.setEstadoCliente(estado);
            
            if(clienteData.actualizarCliente(clienteEncontrado)){
                JOptionPane.showMessageDialog(this, "Cliente actualizado exitosamente.","Exito",JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el cliente", "Error", JOptionPane.ERROR_MESSAGE);
            } 
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El campo 'Edad' debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al actualizar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jbActualizarClienteActionPerformed

    private void jbEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarClienteActionPerformed
        //ESTE TAMBIÉN FUNCIONA
        if (clienteEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Debe buscar un cliente para poder eliminar");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea ELIMINAR PERMANENTEMENTE a este cliente?\nEsta acción no se puede deshacer.", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);
    
        if (confirmacion == JOptionPane.YES_OPTION) {
        
        if (clienteData.eliminarCliente(clienteEncontrado.getCodCli())) {
            JOptionPane.showMessageDialog(this, "Cliente eliminado permanentemente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar al cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jbEliminarClienteActionPerformed

    private void jbCambiarEstadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarEstadoClienteActionPerformed
        //Y ESTE HAY QUE CORREGIRLO POR QUE TE DEJA CAMBIAR EL ESTADO A INACTIVO NOMÁS Y DESPUÉS NO TE DEJA CAMBIARLO DE NUEVO A ACTIVO, AUNQUE TIENE EL MISMO PROBLEMA QUE EL DE ACTUALIZAR
        //SALEN LOS DOS POP UPS Y LEAN BIEN QUE POP UPS TOMA PARA SABER QUE CORREGIR  (EL CLIENTE FUE DADO DE BAJA CORRECTAMENTE DEL METODO CAMBIARESTADOCLIENTE  DE LA CLASE CLIENTEDATA)
        //Y EL POP UP DE (NO SE PUDO CAMBIAR EL ESTADO DEL CLIENTE DE ELSE DEL METODO DE ESTE BOTÓN)
        //CHAU ME VOY A DORMIR NO ROMPAN NADA
        if (clienteEncontrado == null){
            JOptionPane.showMessageDialog(this, "Debe buscar un cliente para cambiar su estado.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean estadoActual = clienteEncontrado.isEstadoCliente();
        boolean nuevoEstado = !estadoActual;
        
        String nuevoEstadoStr = nuevoEstado ? "Activo" : "Inactivo";
        
        if(clienteData.cambiarEstadoCliente(clienteEncontrado.getCodCli(), nuevoEstado)){
            JOptionPane.showMessageDialog(this, "Estado del cliente cambiado a: "+ nuevoEstadoStr,"Exito",JOptionPane.INFORMATION_MESSAGE);
            jcbEstadoCliente.setSelectedItem(nuevoEstadoStr);
            clienteEncontrado.setEstadoCliente(nuevoEstado);
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo cambiar el estado del cliente.","Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbCambiarEstadoClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbActualizarCliente;
    private javax.swing.JButton jbBuscarCliente;
    private javax.swing.JButton jbCambiarEstadoCliente;
    private javax.swing.JButton jbEliminarCliente;
    private javax.swing.JButton jbGuardarCliente;
    private javax.swing.JComboBox<String> jcbAfeccionesCliente;
    private javax.swing.JComboBox<String> jcbEstadoCliente;
    private javax.swing.JLabel jlAfeccionesCliente;
    private javax.swing.JLabel jlDniCliente;
    private javax.swing.JLabel jlEdadCliente;
    private javax.swing.JLabel jlEstadoCliente;
    private javax.swing.JLabel jlGestionClientes;
    private javax.swing.JLabel jlNombreCliente;
    private javax.swing.JLabel jlTelefonoCliente;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfDniCliente;
    private javax.swing.JTextField jtfEdadCliente;
    private javax.swing.JTextField jtfNombreCliente;
    private javax.swing.JTextField jtfTelefonoCliente;
    // End of variables declaration//GEN-END:variables
    private void limpiarCamposMenosDni() {
    jtfNombreCliente.setText("");
    jtfTelefonoCliente.setText("");
    jtfEdadCliente.setText("");
    jcbAfeccionesCliente.setSelectedIndex(0);
    jcbEstadoCliente.setSelectedIndex(0);
    clienteEncontrado = null;
    }
    
    private void limpiarCampos() {
    jtfDniCliente.setText("");
    jtfNombreCliente.setText("");
    jtfTelefonoCliente.setText("");
    jtfEdadCliente.setText("");
    jcbAfeccionesCliente.setSelectedIndex(0);
    jcbEstadoCliente.setSelectedIndex(0);
    clienteEncontrado = null;
    }
}
