
package Vistass;

public class AgregarInstalacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarInstalacion
     */
    public AgregarInstalacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jtfDetalleInstalacion = new javax.swing.JTextField();
        jcbEstadoInstalacion = new javax.swing.JComboBox<>();
        jbBuscarInstalacion = new javax.swing.JButton();
        jtfPrecioInstalacion = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jbGuardarInstalacion = new javax.swing.JButton();
        jlNombreInstalacion = new javax.swing.JLabel();
        jbActualizarInstalacion = new javax.swing.JButton();
        jlDetalleInstalacion = new javax.swing.JLabel();
        jbEliminarInstalacion = new javax.swing.JButton();
        jlGestionInstalaciones = new javax.swing.JLabel();
        jbCambiarEstadoInstalacion = new javax.swing.JButton();
        jlPrecioInstalacion = new javax.swing.JLabel();
        jtfNombreInstalacion = new javax.swing.JTextField();
        jlEstadoInstalacion = new javax.swing.JLabel();

        label1.setText("label1");

        jcbEstadoInstalacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstadoInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoInstalacionActionPerformed(evt);
            }
        });

        jbBuscarInstalacion.setText("Buscar");

        jtfPrecioInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecioInstalacionActionPerformed(evt);
            }
        });

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setText("Spa Entre Dedos");

        jbGuardarInstalacion.setText("Guardar");
        jbGuardarInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarInstalacionActionPerformed(evt);
            }
        });

        jlNombreInstalacion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlNombreInstalacion.setForeground(new java.awt.Color(69, 54, 14));
        jlNombreInstalacion.setText("Nombre:");

        jbActualizarInstalacion.setText("Actualizar");

        jlDetalleInstalacion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlDetalleInstalacion.setForeground(new java.awt.Color(69, 54, 14));
        jlDetalleInstalacion.setText("Detalle de uso:");

        jbEliminarInstalacion.setText("Eliminar");
        jbEliminarInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarInstalacionActionPerformed(evt);
            }
        });

        jlGestionInstalaciones.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jlGestionInstalaciones.setText("Gestion Instalaciones");

        jbCambiarEstadoInstalacion.setText("Cambiar Estado");

        jlPrecioInstalacion.setText("Precio x 30 minutos:");

        jlEstadoInstalacion.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlDetalleInstalacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfDetalleInstalacion)
                    .addComponent(jtfNombreInstalacion)
                    .addComponent(jtfPrecioInstalacion)
                    .addComponent(jlPrecioInstalacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jlNombreInstalacion))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlEstadoInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbBuscarInstalacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbEstadoInstalacion, javax.swing.GroupLayout.Alignment.LEADING, 0, 182, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlGestionInstalaciones)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbGuardarInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbActualizarInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCambiarEstadoInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEliminarInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionInstalaciones)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbBuscarInstalacion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlNombreInstalacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombreInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jlDetalleInstalacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDetalleInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfPrecioInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEstadoInstalacion)
                            .addComponent(jlPrecioInstalacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbEstadoInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarInstalacion)
                    .addComponent(jbEliminarInstalacion))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizarInstalacion)
                    .addComponent(jbCambiarEstadoInstalacion))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPrecioInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecioInstalacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecioInstalacionActionPerformed

    private void jbGuardarInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarInstalacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGuardarInstalacionActionPerformed

    private void jcbEstadoInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoInstalacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstadoInstalacionActionPerformed

    private void jbEliminarInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarInstalacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEliminarInstalacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbActualizarInstalacion;
    private javax.swing.JButton jbBuscarInstalacion;
    private javax.swing.JButton jbCambiarEstadoInstalacion;
    private javax.swing.JButton jbEliminarInstalacion;
    private javax.swing.JButton jbGuardarInstalacion;
    private javax.swing.JComboBox<String> jcbEstadoInstalacion;
    private javax.swing.JLabel jlDetalleInstalacion;
    private javax.swing.JLabel jlEstadoInstalacion;
    private javax.swing.JLabel jlGestionInstalaciones;
    private javax.swing.JLabel jlNombreInstalacion;
    private javax.swing.JLabel jlPrecioInstalacion;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfDetalleInstalacion;
    private javax.swing.JTextField jtfNombreInstalacion;
    private javax.swing.JTextField jtfPrecioInstalacion;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
