
package Vistass;

import Modeloo.Cliente;
import Modeloo.Conexion;
import Persistencia.ClienteData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.mariadb.jdbc.Connection;

public class InfoCliente extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private ClienteData clienteData;
    private Connection con;
    
    public InfoCliente() {
        initComponents();
        con = (Connection) Conexion.getConexion();
        clienteData = new ClienteData(con);
        modeloTabla = (DefaultTableModel) jtCliente.getModel();
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlInfoClientes = new javax.swing.JLabel();
        jcbCliente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCliente = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jlInfoClientes.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlInfoClientes.setForeground(new java.awt.Color(69, 97, 11));
        jlInfoClientes.setText("Informacion de Clientes");

        jcbCliente.setBackground(new java.awt.Color(242, 242, 242));
        jcbCliente.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jcbCliente.setForeground(new java.awt.Color(69, 54, 14));
        jcbCliente.setBorder(null);
        jcbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClienteActionPerformed(evt);
            }
        });

        jtCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Dni", "Nombre", "Telefono", "Edad", "Afecciones", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtCliente);
        if (jtCliente.getColumnModel().getColumnCount() > 0) {
            jtCliente.getColumnModel().getColumn(0).setResizable(false);
            jtCliente.getColumnModel().getColumn(1).setResizable(false);
            jtCliente.getColumnModel().getColumn(2).setResizable(false);
            jtCliente.getColumnModel().getColumn(3).setResizable(false);
            jtCliente.getColumnModel().getColumn(4).setResizable(false);
            jtCliente.getColumnModel().getColumn(5).setResizable(false);
            jtCliente.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTitulo))
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jlInfoClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlInfoClientes)
                .addGap(24, 24, 24)
                .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClienteActionPerformed
        limpiarTabla();
        // 2. Obtiene el cliente seleccionado del ComboBox
        Cliente clienteSeleccionado = (Cliente) jcbCliente.getSelectedItem();
        // (Esto puede ser null si el combo está vacío o se está inicializando)
        if (clienteSeleccionado == null) {
            return;
        }
        // 3. Convierte los datos del cliente a un formato para la tabla
        String afecciones = clienteSeleccionado.isAfecciones() ? "Si" : "No";
        String estado = clienteSeleccionado.isEstadoCliente() ? "Activo" : "Inactivo";
        // 4. Añade la fila a la tabla
        modeloTabla.addRow(new Object[]{
            clienteSeleccionado.getCodCli(),
            clienteSeleccionado.getDni(),
            clienteSeleccionado.getNombreCliente(),
            clienteSeleccionado.getTelefonoCliente(),
            clienteSeleccionado.getEdad(),
            afecciones,
            estado
        });
        
    }//GEN-LAST:event_jcbClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Cliente> jcbCliente;
    private javax.swing.JLabel jlInfoClientes;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtCliente;
    // End of variables declaration//GEN-END:variables
    private void cargarComboBox(){
        List<Cliente> clientes = clienteData.listarClientes();
        
        jcbCliente.removeAllItems();
        
        for(Cliente cliente : clientes){
            jcbCliente.addItem(cliente);
        }
    }
    private void limpiarTabla() {
        // (Asegúrate de que tu DefaultTableModel se llame modeloTabla)
        modeloTabla.setRowCount(0);
    }
}
