
package Vistass;

import Modeloo.Cliente;
import Modeloo.Conexion;
import Modeloo.Sesion;
import Persistencia.ClienteData;
import Persistencia.SesionData;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.mariadb.jdbc.Connection;

public class InfoSesion extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private SesionData sesionData;
    private ClienteData clienteData;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    
    public InfoSesion() {
        initComponents();
        this.modeloTabla = new DefaultTableModel();
        this.sesionData = new SesionData((Connection) Conexion.getConexion());
        this.clienteData = new ClienteData((Connection) Conexion.getConexion());
        
        armarCabeceraTabla();
        cargarClientesEnComboBox();
        jcbSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSesionesActionPerformed(evt);
            }
        });
        limpiarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlGestionClientes = new javax.swing.JLabel();
        jcbSesiones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSesion = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jlGestionClientes.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlGestionClientes.setForeground(new java.awt.Color(69, 97, 11));
        jlGestionClientes.setText("Informacion de Sesiones");

        jcbSesiones.setBackground(new java.awt.Color(242, 242, 242));
        jcbSesiones.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jcbSesiones.setForeground(new java.awt.Color(69, 54, 14));
        jcbSesiones.setBorder(null);
        jcbSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSesionesActionPerformed(evt);
            }
        });

        jtSesion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sesion", "Incio", "Fin", "Tratamiento", "Masajista", "Pack", "Instalacion", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtSesion);
        if (jtSesion.getColumnModel().getColumnCount() > 0) {
            jtSesion.getColumnModel().getColumn(0).setResizable(false);
            jtSesion.getColumnModel().getColumn(1).setResizable(false);
            jtSesion.getColumnModel().getColumn(2).setResizable(false);
            jtSesion.getColumnModel().getColumn(3).setResizable(false);
            jtSesion.getColumnModel().getColumn(4).setResizable(false);
            jtSesion.getColumnModel().getColumn(5).setResizable(false);
            jtSesion.getColumnModel().getColumn(6).setResizable(false);
            jtSesion.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jlGestionClientes))
                    .addComponent(jlTitulo))
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionClientes)
                .addGap(18, 18, 18)
                .addComponent(jcbSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSesionesActionPerformed
        
        Object item = jcbSesiones.getSelectedItem();
        
        if (item == null) {
            limpiarTabla();
            return;
        }
        Cliente clienteSeleccionado = (Cliente) item;
        cargarDatosTabla(clienteSeleccionado.getCodCli());
    }//GEN-LAST:event_jcbSesionesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Cliente> jcbSesiones;
    private javax.swing.JLabel jlGestionClientes;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtSesion;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceraTabla() {
        modeloTabla.addColumn("Sesion");
        modeloTabla.addColumn("Inicio");
        modeloTabla.addColumn("Fin");
        modeloTabla.addColumn("Tratamiento");
        modeloTabla.addColumn("Masajista");
        modeloTabla.addColumn("Pack");
        modeloTabla.addColumn("Instalacion");
        modeloTabla.addColumn("Estado");
        jtSesion.setModel(modeloTabla);
    }
    
    private void cargarClientesEnComboBox() {
        jcbSesiones.removeAllItems(); //

        List<Cliente> clientesActivos = clienteData.listarClientesActivos();
        for (Cliente cliente : clientesActivos) {
            jcbSesiones.addItem(cliente); 
        }
        
        if (!clientesActivos.isEmpty()) {
            cargarDatosTabla(clientesActivos.get(0).getCodCli());
        }
    }
    
    private void limpiarTabla() {
        modeloTabla.setRowCount(0);
    }
    
    private void cargarDatosTabla(int codCli) {
        limpiarTabla();
        List<Sesion> sesiones = sesionData.listarSesionesPorCliente(codCli);
        
        for (Sesion s : sesiones) {
            modeloTabla.addRow(new Object[]{
                s.getCodSesion(),
                s.getFechaInicio().format(formatter),
                s.getFechaFin().format(formatter),
                s.getCodTratamiento(),
                s.getCodMasajista(),
                s.getCodPack(),
                s.getCodInstal(),
                s.isEstadoInstalacion() ? "Activo" : "Inactivo"
            });
        }
    }
}
