
package Vistass;

public class ListarInstalaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarInstalaciones
     */
    public ListarInstalaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlGestionClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaInstalaciones = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jlGestionClientes.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlGestionClientes.setForeground(new java.awt.Color(69, 97, 11));
        jlGestionClientes.setText("Lista de Instalaciones");

        jtListaInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Detalle", "Precio x 30min", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaInstalaciones);
        if (jtListaInstalaciones.getColumnModel().getColumnCount() > 0) {
            jtListaInstalaciones.getColumnModel().getColumn(0).setResizable(false);
            jtListaInstalaciones.getColumnModel().getColumn(1).setResizable(false);
            jtListaInstalaciones.getColumnModel().getColumn(2).setResizable(false);
            jtListaInstalaciones.getColumnModel().getColumn(3).setResizable(false);
            jtListaInstalaciones.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jlGestionClientes)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionClientes)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlGestionClientes;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtListaInstalaciones;
    // End of variables declaration//GEN-END:variables
}
