
package Vistass;

import Modeloo.Conexion;
import Modeloo.Sesion;
import Persistencia.SesionData;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.mariadb.jdbc.Connection;

public class ListarSesiones extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private SesionData sesionData;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    
    public ListarSesiones() {
        initComponents();
        this.modeloTabla = new DefaultTableModel();
        this.sesionData = new SesionData((Connection) Conexion.getConexion());
        armarCabeceraTabla();
        cargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlListaMasajistasDispo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaSesiones = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jlListaMasajistasDispo.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlListaMasajistasDispo.setForeground(new java.awt.Color(69, 97, 11));
        jlListaMasajistasDispo.setText("Lista de Sesiones");

        jtListaSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Inicio", "Fin", "Tratamiento", "Masajista", "Pack", "Instalacion", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaSesiones);
        if (jtListaSesiones.getColumnModel().getColumnCount() > 0) {
            jtListaSesiones.getColumnModel().getColumn(0).setResizable(false);
            jtListaSesiones.getColumnModel().getColumn(1).setResizable(false);
            jtListaSesiones.getColumnModel().getColumn(3).setResizable(false);
            jtListaSesiones.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jlListaMasajistasDispo)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlListaMasajistasDispo)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlListaMasajistasDispo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtListaSesiones;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceraTabla() {

        modeloTabla.addColumn("Codigo");
        modeloTabla.addColumn("Inicio");
        modeloTabla.addColumn("Fin");
        modeloTabla.addColumn("Tratamiento");
        modeloTabla.addColumn("Masajista");
        modeloTabla.addColumn("Pack");
        modeloTabla.addColumn("Instalacion");
        modeloTabla.addColumn("Estado");
        jtListaSesiones.setModel(modeloTabla);
    }
    
    private void cargarDatosTabla() {

        modeloTabla.setRowCount(0);
        List<Sesion> sesiones = sesionData.listarSesiones();
        for (Sesion s : sesiones) {
            modeloTabla.addRow(new Object[]{
                s.getCodSesion(),
                s.getFechaInicio().format(formatter),
                s.getFechaFin().format(formatter),
                s.getCodTratamiento(),
                s.getCodMasajista(),
                s.getCodPack(),
                s.getCodInstal(),
                s.isEstadoInstalacion() ? "Activo" : "Inactivo"
            });
        }
    }
}

