
package Vistass;

import Modeloo.Conexion;
import Modeloo.Masaje;
import Persistencia.MasajeData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.mariadb.jdbc.Connection;

public class ListarMasajes extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private Connection con;
    private MasajeData masajeData;
    
    public ListarMasajes() {
        initComponents();
        con = (Connection) Conexion.getConexion();
        masajeData = new MasajeData(con);
        modeloTabla = (DefaultTableModel) jtListaMasaje.getModel();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlListaMasajes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaMasaje = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jlListaMasajes.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlListaMasajes.setForeground(new java.awt.Color(69, 97, 11));
        jlListaMasajes.setText("Lista de Tratamientos");

        jtListaMasaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Detalle", "Duracion", "Costo", "Estado", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaMasaje);
        if (jtListaMasaje.getColumnModel().getColumnCount() > 0) {
            jtListaMasaje.getColumnModel().getColumn(0).setResizable(false);
            jtListaMasaje.getColumnModel().getColumn(1).setResizable(false);
            jtListaMasaje.getColumnModel().getColumn(2).setResizable(false);
            jtListaMasaje.getColumnModel().getColumn(3).setResizable(false);
            jtListaMasaje.getColumnModel().getColumn(4).setResizable(false);
            jtListaMasaje.getColumnModel().getColumn(5).setResizable(false);
            jtListaMasaje.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlListaMasajes)
                        .addGap(67, 67, 67)))
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlListaMasajes)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlListaMasajes;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtListaMasaje;
    // End of variables declaration//GEN-END:variables
    private void cargarTabla() {
        limpiarTabla();
        List<Masaje> masajes = masajeData.listarMasajes();
        
        for (Masaje masaje : masajes) {
            String estado = masaje.isActivo() ? "Activo" : "Inactivo";
            
            modeloTabla.addRow(new Object[]{
                masaje.getCodTratamiento(),
                masaje.getNombreTratamiento(),
                masaje.getDetalleTratamiento(),
                masaje.getDuracionTratamiento(),
                masaje.getCostoTratamiento(),
                estado,
                masaje.getTipo().toString()
            });
        }
    }
    private void limpiarTabla() {
        modeloTabla.setRowCount(0);
    }
}
