
package Vistass;

import Modeloo.Cliente;
import Modeloo.Conexion;
import Persistencia.ClienteData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.mariadb.jdbc.Connection;

public class ListarClientes extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private Connection con;
    private ClienteData clienteData;
    
    public ListarClientes() {
        initComponents();
        con = (Connection) Conexion.getConexion();
        clienteData = new ClienteData(con);
        modeloTabla = (DefaultTableModel) jtListaClientes.getModel();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlGestionClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaClientes = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setBorder(null);
        setClosable(true);

        jlTitulo.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(69, 97, 11));
        jlTitulo.setText("Spa Entre Dedos");

        jlGestionClientes.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jlGestionClientes.setForeground(new java.awt.Color(69, 97, 11));
        jlGestionClientes.setText("Lista de Clientes");

        jtListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Dni", "Nombre", "Telefono", "Edad", "Afecciones", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaClientes);
        if (jtListaClientes.getColumnModel().getColumnCount() > 0) {
            jtListaClientes.getColumnModel().getColumn(0).setResizable(false);
            jtListaClientes.getColumnModel().getColumn(1).setResizable(false);
            jtListaClientes.getColumnModel().getColumn(2).setResizable(false);
            jtListaClientes.getColumnModel().getColumn(3).setResizable(false);
            jtListaClientes.getColumnModel().getColumn(4).setResizable(false);
            jtListaClientes.getColumnModel().getColumn(5).setResizable(false);
            jtListaClientes.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jlGestionClientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jlTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGestionClientes)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlGestionClientes;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtListaClientes;
    // End of variables declaration//GEN-END:variables
    private void cargarTabla(){
        limpiarTabla();
        
        List<Cliente> clientes = clienteData.listarClientes();
        
        for(Cliente cliente : clientes){
            String afecciones = cliente.isAfecciones() ? "Si" : "No";
            String estado = cliente.isEstadoCliente() ? "Activo" : "Inactivo";
            
            modeloTabla.addRow(new Object[]{
                cliente.getCodCli(),
                cliente.getDni(),
                cliente.getNombreCliente(),
                cliente.getTelefonoCliente(),
                cliente.getEdad(),
                afecciones,estado
            });
        }
    }

    private void limpiarTabla() {
        modeloTabla.setRowCount(0);
    }
}
