
package Vistass;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(600, 640);
        ajustarIconosMenu();
    }

           private ImageIcon escalarIcono(String ruta, int ancho, int alto) {
            ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
            Image img = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            return new ImageIcon(img);
}
        private void ajustarIconosMenu() {
            jmClientes.setText("");
            jmSesiones.setText("");
            jmMasajes.setText("");
            jmMasajistas.setText("");
            jmInstalaciones.setText("");
            jmReportes.setText("");

            jmClientes.setIcon(escalarIcono("/Recursos/clientes.png", 45, 45));
            jmMasajistas.setIcon(escalarIcono("/Recursos/masajistas.png", 45, 45));
            jmInstalaciones.setIcon(escalarIcono("/Recursos/instalaciones.png", 45, 45));
            jmReportes.setIcon(escalarIcono("/Recursos/reportes.png", 45, 45));
            jmSesiones.setIcon(escalarIcono("/Recursos/sesiones.png", 45, 45));
            jmMasajes.setIcon(escalarIcono("/Recursos/masajes.png", 55, 55));         
            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        ImageIcon fondo = new ImageIcon(getClass().getResource("/Recursos/fondo1.jpg"));
        Image miImagen = fondo.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen, 0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        jMenuBar1 = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiAgregarCliente = new javax.swing.JMenuItem();
        jmiInfoCliente = new javax.swing.JMenuItem();
        jmiListarClientes = new javax.swing.JMenuItem();
        jmSesiones = new javax.swing.JMenu();
        jmiAgregarSesion = new javax.swing.JMenuItem();
        jmiInfoSesion = new javax.swing.JMenuItem();
        jmiListarSesiones = new javax.swing.JMenuItem();
        jmMasajistas = new javax.swing.JMenu();
        jmiAgregarMasajista = new javax.swing.JMenuItem();
        jmiListarMasajistasDispo = new javax.swing.JMenuItem();
        jmInstalaciones = new javax.swing.JMenu();
        jmiAgregarInstalacion = new javax.swing.JMenuItem();
        jmiListarInstalaciones = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmiReporteDiaSpa = new javax.swing.JMenuItem();
        jmiReporteSolicitados = new javax.swing.JMenuItem();
        jmMasajes = new javax.swing.JMenu();
        jmiAgregarMasaje = new javax.swing.JMenuItem();
        jmiListarMasajes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(60, 60));

        jmClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/clientes.png"))); // NOI18N
        jmClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmClientes.setMaximumSize(new java.awt.Dimension(60, 60));
        jmClientes.setMinimumSize(new java.awt.Dimension(50, 50));
        jmClientes.setPreferredSize(new java.awt.Dimension(100, 100));

        jmiAgregarCliente.setText("Gestion Clientes");
        jmiAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiAgregarCliente);

        jmiInfoCliente.setText("Info Cliente");
        jmiInfoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInfoClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiInfoCliente);

        jmiListarClientes.setText("Listar Clientes");
        jmiListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarClientesActionPerformed(evt);
            }
        });
        jmClientes.add(jmiListarClientes);

        jMenuBar1.add(jmClientes);

        jmSesiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/sesiones.png"))); // NOI18N
        jmSesiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmSesiones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmSesiones.setMaximumSize(new java.awt.Dimension(60, 60));
        jmSesiones.setMinimumSize(new java.awt.Dimension(50, 50));
        jmSesiones.setPreferredSize(new java.awt.Dimension(100, 100));

        jmiAgregarSesion.setText("Gestion Sesiones");
        jmiAgregarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarSesionActionPerformed(evt);
            }
        });
        jmSesiones.add(jmiAgregarSesion);

        jmiInfoSesion.setText("Info Sesion");
        jmiInfoSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInfoSesionActionPerformed(evt);
            }
        });
        jmSesiones.add(jmiInfoSesion);

        jmiListarSesiones.setText("Listar Sesiones");
        jmiListarSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarSesionesActionPerformed(evt);
            }
        });
        jmSesiones.add(jmiListarSesiones);

        jMenuBar1.add(jmSesiones);

        jmMasajistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/masajistas.png"))); // NOI18N
        jmMasajistas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmMasajistas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmMasajistas.setMaximumSize(new java.awt.Dimension(60, 60));
        jmMasajistas.setMinimumSize(new java.awt.Dimension(50, 50));
        jmMasajistas.setPreferredSize(new java.awt.Dimension(100, 100));

        jmiAgregarMasajista.setText("Gestion Masajistas");
        jmiAgregarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarMasajistaActionPerformed(evt);
            }
        });
        jmMasajistas.add(jmiAgregarMasajista);

        jmiListarMasajistasDispo.setText("Listar Masajistas Dispo");
        jmiListarMasajistasDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarMasajistasDispoActionPerformed(evt);
            }
        });
        jmMasajistas.add(jmiListarMasajistasDispo);

        jMenuBar1.add(jmMasajistas);

        jmInstalaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/instalaciones.png"))); // NOI18N
        jmInstalaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmInstalaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmInstalaciones.setMaximumSize(new java.awt.Dimension(60, 60));
        jmInstalaciones.setMinimumSize(new java.awt.Dimension(50, 50));
        jmInstalaciones.setPreferredSize(new java.awt.Dimension(100, 100));

        jmiAgregarInstalacion.setText("Gestion Instalaciones");
        jmiAgregarInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarInstalacionActionPerformed(evt);
            }
        });
        jmInstalaciones.add(jmiAgregarInstalacion);

        jmiListarInstalaciones.setText("Listar Instalaciones");
        jmiListarInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarInstalacionesActionPerformed(evt);
            }
        });
        jmInstalaciones.add(jmiListarInstalaciones);

        jMenuBar1.add(jmInstalaciones);

        jmReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/reportes.png"))); // NOI18N
        jmReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmReportes.setMaximumSize(new java.awt.Dimension(60, 60));
        jmReportes.setMinimumSize(new java.awt.Dimension(50, 50));
        jmReportes.setPreferredSize(new java.awt.Dimension(100, 100));

        jmiReporteDiaSpa.setText("Reporte Dia de Spa");
        jmiReporteDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteDiaSpaActionPerformed(evt);
            }
        });
        jmReportes.add(jmiReporteDiaSpa);

        jmiReporteSolicitados.setText("Reporte Solicitados");
        jmiReporteSolicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteSolicitadosActionPerformed(evt);
            }
        });
        jmReportes.add(jmiReporteSolicitados);

        jMenuBar1.add(jmReportes);

        jmMasajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/masajes.png"))); // NOI18N
        jmMasajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmMasajes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jmMasajes.setMaximumSize(new java.awt.Dimension(60, 60));
        jmMasajes.setMinimumSize(new java.awt.Dimension(50, 50));
        jmMasajes.setPreferredSize(new java.awt.Dimension(100, 100));

        jmiAgregarMasaje.setText("Gestion Masajes");
        jmiAgregarMasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarMasajeActionPerformed(evt);
            }
        });
        jmMasajes.add(jmiAgregarMasaje);

        jmiListarMasajes.setText("Listar Masajes");
        jmiListarMasajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarMasajesActionPerformed(evt);
            }
        });
        jmMasajes.add(jmiListarMasajes);

        jMenuBar1.add(jmMasajes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiInfoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInfoClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        InfoCliente infocliente = new InfoCliente();
        infocliente.setVisible(true);
        infocliente.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(infocliente);
    }//GEN-LAST:event_jmiInfoClienteActionPerformed

    private void jmiAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AgregarCliente cliente = new AgregarCliente();
        cliente.setVisible(true);
        cliente.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(cliente);
        
    }//GEN-LAST:event_jmiAgregarClienteActionPerformed

    private void jmiListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarClientesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListarClientes listaclientes = new ListarClientes();
        listaclientes.setVisible(true);
        listaclientes.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(listaclientes);
        
    }//GEN-LAST:event_jmiListarClientesActionPerformed

    private void jmiAgregarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarSesionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AgregarSesion sesion = new AgregarSesion();
        sesion.setVisible(true);
        sesion.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(sesion);
        
    }//GEN-LAST:event_jmiAgregarSesionActionPerformed

    private void jmiAgregarMasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarMasajeActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AgregarMasaje masaje = new AgregarMasaje();
        masaje.setVisible(true);
        masaje.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(masaje);
        
    }//GEN-LAST:event_jmiAgregarMasajeActionPerformed

    private void jmiAgregarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarMasajistaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AgregarMasajista masajista = new AgregarMasajista();
        masajista.setVisible(true);
        masajista.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(masajista);
        
    }//GEN-LAST:event_jmiAgregarMasajistaActionPerformed

    private void jmiAgregarInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarInstalacionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AgregarInstalacion instalacion = new AgregarInstalacion();
        instalacion.setVisible(true);
        instalacion.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(instalacion);
        
    }//GEN-LAST:event_jmiAgregarInstalacionActionPerformed

    private void jmiInfoSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInfoSesionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        InfoSesion infosesion = new InfoSesion();
        infosesion.setVisible(true);
        infosesion.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(infosesion);
        
    }//GEN-LAST:event_jmiInfoSesionActionPerformed

    private void jmiListarSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarSesionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListarSesiones listasesiones = new ListarSesiones();
        listasesiones.setVisible(true);
        listasesiones.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(listasesiones);
        
    }//GEN-LAST:event_jmiListarSesionesActionPerformed

    private void jmiListarMasajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarMasajesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListarMasajes listamasajes = new ListarMasajes();
        listamasajes.setVisible(true);
        listamasajes.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(listamasajes);
        
    }//GEN-LAST:event_jmiListarMasajesActionPerformed

    private void jmiListarMasajistasDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarMasajistasDispoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListarMasajistasDispo masajistasdispo= new ListarMasajistasDispo();
        masajistasdispo.setVisible(true);
        masajistasdispo.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(masajistasdispo);
        
    }//GEN-LAST:event_jmiListarMasajistasDispoActionPerformed

    private void jmiListarInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarInstalacionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListarInstalaciones listainstalaciones = new ListarInstalaciones();
        listainstalaciones.setVisible(true);
        listainstalaciones.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(listainstalaciones);
        
    }//GEN-LAST:event_jmiListarInstalacionesActionPerformed

    private void jmiReporteDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteDiaSpaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ReporteDiaSpa reportespa = new ReporteDiaSpa();
        reportespa.setVisible(true);
        reportespa.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(reportespa);
        
    }//GEN-LAST:event_jmiReporteDiaSpaActionPerformed

    private void jmiReporteSolicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteSolicitadosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ReporteSolicitados reportesolicitados = new ReporteSolicitados();
        reportesolicitados.setVisible(true);
        reportesolicitados.getContentPane().setBackground(new Color(242,242,242));
        escritorio.add(reportesolicitados);
        
    }//GEN-LAST:event_jmiReporteSolicitadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmInstalaciones;
    private javax.swing.JMenu jmMasajes;
    private javax.swing.JMenu jmMasajistas;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenu jmSesiones;
    private javax.swing.JMenuItem jmiAgregarCliente;
    private javax.swing.JMenuItem jmiAgregarInstalacion;
    private javax.swing.JMenuItem jmiAgregarMasaje;
    private javax.swing.JMenuItem jmiAgregarMasajista;
    private javax.swing.JMenuItem jmiAgregarSesion;
    private javax.swing.JMenuItem jmiInfoCliente;
    private javax.swing.JMenuItem jmiInfoSesion;
    private javax.swing.JMenuItem jmiListarClientes;
    private javax.swing.JMenuItem jmiListarInstalaciones;
    private javax.swing.JMenuItem jmiListarMasajes;
    private javax.swing.JMenuItem jmiListarMasajistasDispo;
    private javax.swing.JMenuItem jmiListarSesiones;
    private javax.swing.JMenuItem jmiReporteDiaSpa;
    private javax.swing.JMenuItem jmiReporteSolicitados;
    // End of variables declaration//GEN-END:variables
}
